language: node_js
node_js:
  - "10.15.1"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.14.0
  - export PATH="$HOME/.yarn/bin:$PATH"
cache:
  yarn: true
  directories:
    - "node_modules"
jobs:
  include:
    - stage: "Tests" # naming the Tests stage
      name: "Unit Tests" # names the first Tests stage job
      script: yarn test
    - stage: "build"
      name: "building project" # names the second Tests stage job
      script:
        - echo "passed the test now building"
        - yarn build
        - git add .
        - git commit -m "ready to deploy"
    - stage: "deploy"
      name: "Deploy to heroku"
      if: branch = master
      script: skip
      deploy:
        provider: heroku
        api_key:
          secure: $HEROKU_DEPLOY_KEY
        app: read-meee
        on:
          repo: Siddant/project-4
